# Project information
site_name: SeleniumBase Docs
site_url: https://seleniumbase.io
site_author: Michael Mintz
site_description: A complete framework for end-to-end testing with Python, pytest, behave-BDD, and WebDriver.
# Repository information
repo_name: seleniumbase/SeleniumBase
repo_url: https://github.com/seleniumbase/SeleniumBase
edit_uri: ""
site_dir: "site"
docs_dir: "mkdocs_build"
# Copyright
copyright: Copyright &copy; 2014 - 2022 Michael Mintz
# Extensions
markdown_extensions:
  - admonition
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  # - pymdownx.details
  # - pymdownx.snippets
# Configuration
theme:
  name: material
  logo: img/logo3c.png
  favicon: img/green_logo3.png
  language: en
  include_homepage_in_sidebar: true
  sticky_navigation: true
  collapse_navigation: true
  # titles_only: false
  include_search_page: false
  search_index_only: true
  static_templates:
    - 404.html
  features:
    # - search.highlight
    # - toc.integrate
    - toc.hide
    # - navigation.indexes
    - toc.follow
    - navigation.sections
    # - navigation.expand
    # - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.instant
  palette:
    scheme: default
    primary: blue
    accent: green
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: img/sb_logo_10.png
# Plugins
plugins:
  - search:
      separator: '[\s]+'
      lang: en
  - exclude-search:
      exclude:
        - CODE_OF_CONDUCT.md
        - CONTRIBUTING.md
        - SECURITY.md
        - examples/case_summary.md
        - help_docs/chinese.md
        - help_docs/mysql_installation.md
        - integrations/katalon/ReadMe.md
        - help_docs/verify_webdriver.md
        - help_docs/webdriver_installation.md
        - seleniumbase/utilities/selenium_ide/ReadMe.md
        - seleniumbase/examples/chart_maker/ReadMe.md
  - minify:
      minify_html: true
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: mkdocs_build.prepare:main
# Page tree
nav:
  - ✅ SeleniumBase README: README.md
  - 🏰 List of Features: help_docs/features_list.md
  - 📚 Running Example Tests: examples/ReadMe.md
  - 🎛️ Command Line Options: help_docs/customizing_test_runs.md
  - 🌠 Console Scripts: seleniumbase/console_scripts/ReadMe.md
  - 📊 Dashboard / Reports: examples/example_logs/ReadMe.md
  - 🔡 Syntax Formats: help_docs/syntax_formats.md
  - 🎖️ GUI / Commander: help_docs/commander.md
  - ⏺️ Recorder Mode: help_docs/recorder_mode.md
  - 📘 API Reference: help_docs/method_summary.md
  - Python Setup / Install:
    - 🐉 Get Python, pip, & git: help_docs/install_python_pip_git.md
    - ⚙️ Virtualenv Instructions: help_docs/virtualenv_instructions.md
    - 🏄 Install SeleniumBase: help_docs/install.md
    - 👁️ How it Works: help_docs/how_it_works.md
  - JS Manager / JS Tools:
    - 🕹️ Package Manager: help_docs/js_package_manager.md
    - 🎦 Demo Mode: help_docs/demo_mode.md
    - 🚎 Tour Maker: examples/tour_examples/ReadMe.md
    - 🛂 Dialog Boxes: examples/dialog_boxes/ReadMe.md
    - 📶 Chart Maker: help_docs/chart_maker.md
    - 🎞️ Presentation Maker: examples/presenter/ReadMe.md
  - Integrations:
    - 📱 Mobile Testing: help_docs/mobile_testing.md
    - 🤖 GitHub CI: integrations/github/workflows/ReadMe.md
    - 🗂️ Case Plans: help_docs/case_plans.md
    - 🖼️ Visual Testing: examples/visual_testing/ReadMe.md
    - 🕵️ The HTML Inspector: help_docs/html_inspector.md
    - 🌐 Selenium Grid: seleniumbase/utilities/selenium_grid/ReadMe.md
    - 📶 HighCharts: examples/chart_maker/ReadMe.md
    - 🛂 MasterQA: examples/master_qa/ReadMe.md
    - 🤖 Azure Pipelines: integrations/azure/azure_pipelines/ReadMe.md
    - 🤖 Jenkins on Azure: integrations/azure/jenkins/ReadMe.md
    - 🤖 Jenkins on Google Cloud: integrations/google_cloud/ReadMe.md
    - 🤖 NodeJS Test Runner: https://github.com/seleniumbase/SeleniumBase/tree/master/integrations/node_js
  - Presentations:
    - ✅ Core Presentation: https://seleniumbase.io/other/core_presentation.html
    - 🎞️ Presenter Demo: https://seleniumbase.io/other/presenter.html
    - 📊 Chart Maker Demo: https://seleniumbase.io/other/chart_presentation.html
    - ⚙️ Python Virtual Envs: https://seleniumbase.io/other/py_virtual_envs.html
  - Demo Pages:
    - 📑 Demo Page (Test Page): https://seleniumbase.io/demo_page
    - 🔑 MFA Login (Test App): https://seleniumbase.io/realworld/login
    - 📝 TinyMCE (Test Page): https://seleniumbase.io/tinymce/
    - 🔢 Calculator (Test App): https://seleniumbase.io/apps/calculator
    - 📱 Device Farm (Virtual): https://seleniumbase.io/devices/
    - ⚠️ Error Page (Test Page): https://seleniumbase.io/error_page/
    - ⚠️ Page with broken links: https://seleniumbase.io/other/broken_page
    - ↔️ Drag & Drop (Test Page): https://seleniumbase.io/other/drag_and_drop
    - 🖼️ Canvas Test Page One: https://seleniumbase.io/canvas/
    - 🖼️ Canvas Test Page Two: https://seleniumbase.io/other/canvas
    - 👤 Shadow DOM/Root Page: https://seleniumbase.io/other/shadow_dom
    - 🖥️ SeleniumBase in iframe: https://seleniumbase.io/w3schools/sbase
    - 🖥️ W3Schools Playground: https://seleniumbase.io/w3schools/
    - 🖥️ W3Schools iframes: https://seleniumbase.io/w3schools/iframes
    - 🗃️ W3Schools file upload: https://seleniumbase.io/w3schools/file_upload
    - 🖲️ W3Schools doubleclick: https://seleniumbase.io/w3schools/double_click
    - ↔️ W3Schools drag & drop: https://seleniumbase.io/w3schools/drag_drop
    - ☑️ W3Schools checkboxes: https://seleniumbase.io/w3schools/checkboxes
    - 🔘 W3Schools radio buttons: https://seleniumbase.io/w3schools/radio_buttons
  - Additional Help Docs:
    - 📑 Table of Contents: help_docs/ReadMe.md
    - 🔐 Decorators / Security: seleniumbase/common/ReadMe.md
    - 🐳 Docker Start Guide: integrations/docker/ReadMe.md
    - 🗂️ Case Plans (examples): examples/case_summary.md
    - 🧭 Using Safari Driver: help_docs/using_safari_driver.md
    - 👤 Shadow DOM Support: help_docs/shadow_dom.md
    - 👥 macOS Hidden Files: help_docs/hidden_files_info.md
    - 🗄️ MySQL Instructions: help_docs/mysql_installation.md
    - 🛂 Master QA Hybrid Mode: seleniumbase/masterqa/ReadMe.md
    - 📃 Desired Capabilities: help_docs/desired_capabilities.md
    - 📜 Useful grep commands: help_docs/useful_grep_commands.md
    - ⚙️ WebDriver Installation: help_docs/webdriver_installation.md
    - ✔️ Verifying WebDriver: help_docs/verify_webdriver.md
  - Behave-BDD Integration:
    - 🐝 Behave-BDD ReadMe: examples/behave_bdd/ReadMe.md
    - 🐝 Behave-BDD GUI App: help_docs/behave_gui.md
  - Languages:
    - 🌏 Translations: help_docs/translations.md
    - 🐲 Chinese Docs: help_docs/chinese.md
    - 🗾 Locale Codes: help_docs/locale_codes.md
  - Other:
    - 📺 YouTube Link: https://www.youtube.com/playlist?list=PLp9uKicxkBc5UIlGi2BuE3aWC7JyXpD3m
    - 📋 Case Studies: help_docs/happy_customers.md
    - 🙏 Thank You: help_docs/thank_you.md
# Google Analytics
extra:
  analytics:
    provider: google
    # property: G-P5KFWRNLRN
    property: UA-167313767-1
# google_analytics: ['UA-167313767-1', 'seleniumbase.io']